# config.yaml
topicTokenAPI: http://localhost:8280/df/xxx/xxx
services:
  mqtt:
    enable: true
    url: xxxx
    username: 127.0.0.1
    password: 8280
    qos: 0
  redis:
    enable: true
    host: redis
    port: 6379
    dbnum: 9
    poolSize: 10
